langchain-ai/opengpts

.github/workflows/ci.yml, backend/packages/agent-executor/agent_executor/history.py, backend/packages/agent-executor/agent_executor/runnables.py, backend/packages/agent-executor/agent_executor/upload.py, backend/poetry.lock, backend/pyproject.toml, backend/tests/unit_tests/test_imports.py, docker-compose.yml
Run tests locally and remotely
=> Set up tests with redis

backend/app/server.py, backend/tests/unit_tests/app/test_app.py, backend/tests/unit_tests/conftest.py
* Adds a simple unit tests to test one of the api endpoints
=> Add simple unit tests for server

backend/app/server.py, backend/tests/unit_tests/app/test_app.py
Add a bit more validation to endpoints
=> Add some validation to endpoints

frontend/src/components/Config.tsx, frontend/src/components/FileUpload.tsx
Limit file uploads to 10 Mb on the client side.
We can add a corresponding check on the server side.
=> Add dropzone file limit

backend/app/storage.py
* Localize a bit access to REDIS_URL
=> Localize access to REDIS_URL

backend/app/schema.py, backend/app/server.py, backend/app/storage.py, backend/packages/agent-executor/agent_executor/upload.py, backend/poetry.lock, backend/pyproject.toml, backend/tests/unit_tests/app/test_app.py, backend/tests/unit_tests/conftest.py
This is a first pass at adding some schema/validation/docs
=> Add partial validation (first pass)

backend/requirements.txt
This PR fixes some dependencies errors when trying to build the backend and running `langchain serve --port=8100`
Missing dependencies in requirements.txt
- permchain
- python-multipart
I could also specify a version to use here.
I have completed the form and signed the CLA.
Let me know if there is anything more to do from my side!
=> Added permchain and python-multipart libraries to requirements.txt

frontend/src/components/Config.tsx
There was a bug in the Public URL feature that caused the shared_id to be added repeatedly when the page loaded. (http://localhost:5173/?shared_id=474f465e-9701-4bdd-90a4- 392ac966ce94?shared_id=474f465e-9701-4bdd-90a4-392ac966ce94)
To rectify this issue, we implemented a flag in the code to generate the public link only if it is not already available. If the link exists, it will utilize the existing one.
=> Fixing public link issue on page reload

README.md, backend/Dockerfile, docker-compose.yml
- make reload an arg only in docker compose (we dont want reload in prod)
- use redis image which is compatible with arm cpus
=> Fix up docker compose

Dockerfile, backend/Dockerfile
This pull request updates the Dockerfile to replace the deprecated flag "--no-dev" with "--only main" in the "poetry install" command.
This ensures that only the main dependencies are installed and not the dev dependencies.
Fix: #237
=> Fix deprecated flag in Dockerfile

README.md
1. Move Docker Quickstart instructions up so it comes before non-Docker Quickstart.
2. Establish/document pre-requisites early.
3. Establish/document minimal config for Docker launch.
I'm a firm believer in the idea that open source project docs should provide docs that can get a new user from zero to "Hello World" in under 15 minutes or so (time resolving and downloading deps doesn't count. ;) ). 
This is just a quick change that might reduce friction for new users/contributors.
=> Streamline Quickstart Documentation

README.md
I was trying to see how to implement a custom agent, but that path didn't exist, so I wonder if it should be updated.
=> Update agent_types path?

frontend/package.json, frontend/src/App.tsx, frontend/src/api/assistants.ts, frontend/src/api/threads.ts, frontend/src/components/Chat.tsx, frontend/src/components/ChatList.tsx, frontend/src/components/Config.tsx, frontend/src/components/ConfigList.tsx, frontend/src/components/NewChat.tsx, frontend/src/components/NotFound.tsx, frontend/src/components/TypingBox.tsx, frontend/src/hooks/useChatList.ts, frontend/src/hooks/useConfigList.ts, frontend/src/hooks/useThreadAndAssistant.ts, frontend/src/main.tsx, frontend/yarn.lock
Make it simpler to share and navigate the UI by keeping the global state in the URL.
3 URL patterns:
1. `/thread/:chatId` for a chat thread.
2. `/assistant/:assistantId` for a bot config.
3. `/` for creating a new bot.
=> URL based frontend state: React router

README.md, backend/app/parsing.py, backend/app/server.py, backend/tests/unit_tests/agent_executor/test_parsing.py
1. Expand non-Docker quickstart documentation to more thoroughly cover dependency installation and database configuration.
2.  Fix a few `langchain_community` imports and other deprecations.
3. Hard-wrap README markdown to make it easier to digest as text only.
Increase the speed with which new users and developers can get started.
=> Expand non-Docker Quickstart Documentation

backend/app/api/runs.py, backend/app/checkpoint.py, backend/app/upload.py, frontend/src/App.tsx, frontend/src/hooks/useStreamState.tsx
No need to know what assistant id. Thread id is unique and backend can figure out everything else.
This makes it simpler to use the API as less needs to be known.
=> remove assistant_id from run payload

backend/app/agent.py, backend/app/llms.py, backend/app/upload.py
Add an option to use Ollama LLMs for agents
New "Ollama" optyion:
Bot created with the Ollama LLM:
Test Llama2 LLM:
Test OpenChat LLM:
For now, it only supports one Ollama Model. Future Pull Requests will address this shortcoming.
Configuration is currently driven by environment variables:
```shell
export OLLAMA_MODEL=openchat
export OLLAMA_BASE_URL=http://localhost:11434/
```
I will follow up with PRs that model configuration multi-model, and more dynamic.
=> initial implementation of Ollama LLM

backend/app/llms.py
Fix `model` parameter to ChatOllama constructor.
The model parameter name to ChatOllama was wrong, effectively pinning it to the default of "llama2" and preventing usage of other Ollama models.
=> Fix ChatOllama model parameter

backend/app/tools.py
Action Server tool definitions are based on openapi spec that may change.
Do not cache the definitions over requests.
=> fix: Action Server: do not cache tool definitions

API.md, backend/app/api/runs.py, backend/app/api/threads.py, backend/app/storage.py, backend/tests/unit_tests/app/test_app.py, frontend/src/components/Chat.tsx, frontend/src/hooks/useChatMessages.ts
Currently, the OpenGPTs backend only implements `MessageGraph`. Implementing `StateGraph` in the backend demonstrates the ability to support arbitrary graphs within OpenGPTs. Migrating the current usage of `MessageGraph` to `StateGraph` is the first step.
Changes in this PR are adopted from [this PR](https://github.com/langchain-ai/opengpts/pull/257).
1. Rename internal variables and update docstrings: `messages` --> `values`.
2. Add support for `Dict[str, Any]` agent state type: `Sequence[AnyMessage]` --> `Union[Sequence[AnyMessage], Dict[str, Any]]`.
3. Breaking API changes to rename interfaces to be agnostic to a agent state type.
1. `GET /threads/<tid>/messages` --> `GET /threads/<tid>/state`
Response: `{"messages": [...], ...}` --> `{"values": [...], "next": []}`
2. `POST …
=> Update backend API interfaces to be agnostic to messages list (i.e. `MessageGraph`)

.env.example, backend/app/upload.py
Currently, it is possible to use Azure both for chatbot and "chat with your data" use cases but this requires to adjust the environment variables locally to get it to work.
With the following set of environment variables (without OPENAI_API_KEY as we are using Azure-only), it is possible to perform a simple chat but the addition of data (in the assistant or in the chat itself) results in an error :
```
ANTHROPIC_API_KEY=placeholder
YDC_API_KEY=placeholder
TAVILY_API_KEY=placeholder
AZURE_OPENAI_DEPLOYMENT_NAME=placeholder
AZURE_OPENAI_API_KEY=placeholder
AZURE_OPENAI_API_BASE=placeholder
AZURE_OPENAI_API_VERSION=placeholder
CONNERY_RUNNER_URL=https://your-personal-connery-runner-url
CONNERY_RUNNER_API_KEY=placeholder
PROXY_URL=your_proxy_url
POSTGRES_PORT=placeholder …
```
=> Specifying endpoints/deployments for Azure OpenAI embeddings

backend/app/storage.py
Without passing `assistant_id` (in `configurable`) to `aget_state`, `aupdate_state` and `aget_state_history`, the following exception is raised:
`ValueError: Both assistant_id and thread_id must be provided if Retrieval tool is used`.
This happens when Retrieval tool is being used.
=> Fix thread state 500 error (when Retrieval tool is used)

backend/app/api/assistants.py, backend/app/chatbot.py, backend/app/message_types.py, backend/app/storage.py, backend/app/upload.py, frontend/src/components/Config.tsx
Frontend no longer uses this endpoint so there is no use for shared_id. Without that, the endpoint was always returning an empty list.
=> Fix public assistants endpoint

.gitignore, Dockerfile, backend/Dockerfile, backend/Makefile, backend/app/lifespan.py, backend/app/llms.py, backend/app/server.py, backend/app/stream.py, backend/log_config.json, backend/poetry.lock, backend/pyproject.toml
In addition to streaming logs to the console (as it was happening before), logs are now also saved to a rotated file locally. These logs are in JSONL format.
Both of the following are valid and work as expected.
```python
import structlog
logger = structlog.get_logger(__name__)
logger.info("Hello", foo="bar")
```
```python
import logging
logger = logging.getLogger(__name__)
logger.info("Hello", extra={"foo": "bar"})
```
Here's what gets stored in a log file: `{"message": "Hello", "foo": "bar", "logger": "app.api.assistants", "level": "info", "timestamp": "2024-05-06T10:58:05.144324Z"}`. Console simply displays `Hello` (as it would have done before this PR).
=> Use structlog and enable persisting logs in JSONL format

backend/app/api/assistants.py, backend/app/api/threads.py, backend/app/lifespan.py, backend/app/schema.py, backend/app/storage.py, backend/migrations/000004_add_metadata_to_thread.down.sql, backend/migrations/000004_add_metadata_to_thread.up.sql, backend/tests/unit_tests/app/test_app.py, frontend/src/App.tsx, frontend/src/api/assistants.ts, frontend/src/components/ChatList.tsx, frontend/src/components/ConfigList.tsx, frontend/src/components/NewChat.tsx, frontend/src/components/OrphanChat.tsx, frontend/src/hooks/useChatList.ts, frontend/src/hooks/useConfigList.ts, frontend/src/hooks/useThreadAndAssistant.ts, frontend/src/types.ts
As agreed @nfcampos:
- Enables deleting assistants without automatically deleting associated threads.
- Adds metadata column to thread. Column stores the thread's original assistant type: `{"assistant_type": assistant["config"]["configurable"]["type"]}`
- Uses this metadata on the frontend to enable attaching threads to suitable assistants (@andrewnguonly this prevents the issue of deserialization by for example not allowing RAG's thread to be attached to Chatbot).
Ideally, we'd be able to show old messages in the UI for threads without assistants. But unfortunately the current state of things prevents this due to `get_thread_state` depending on the existence of an assistant. So, here's how the UI looks like:
[Screencast from 05-03-2024 11:34:11 …
=> Deleting assistants & attaching orphaned threads to new assistants

backend/app/agent.py, backend/app/llms.py
Add GPT 4o model as an option.
Keep the OpenGPTs project up-to-date with the latest OpenAI model offerings.
=> Add GPT 4o as a model

backend/app/tools.py, backend/poetry.lock, backend/pyproject.toml
`langchain-robocorp`'s version will need to be bumped after this is merged [https://github.com/langchain-ai/langchain/pull/21809](https://github.com/langchain-ai/langchain/pull/21809)
=> Enable passing additional headers to the action server.

backend/app/checkpoint.py
This PR converts `checkpointer.alist` into an async generator by using async for and yield inside the function. With this change, `alist` immediately returns an async iterator, allowing `agent.aget_state_history()` to iterate over it directly without needing to await the coroutine.
https://github.com/langchain-ai/opengpts/issues/377
🐛 Bug Fix
- Modified `checkpointer.alist` to use an async generator pattern python
Tested the flow by calling `get_thread_history()` which internally calls `agent.aget_state_history()`, confirming that the async iteration now functions as expected without errors.
Thank you Team!
=> backend: Convert checkpointer.alist to async generator to fix async iteration in aget_state_history
